### ISSUE TITLE
no extra data found error

### ISSUE THREAD

**Issue by mirh** [lifenjoiner/ISx#1]
[Sample1](http://twdl.cyberlink.com/ftpdload/Patch/CyberLinkBD/HDAdvisor/CDT140213-01/TR140310-017/BD_3DAdvisor_7510_Generic_BD_CDT140213-01.exe).
[Sample2](https://www.mediatek.com/products/broadbandWifi/mt7612u).

**Comment by lifenjoiner** [comment]
Thanks for your feedback!

First, there is no error (please use the v0.3.2).

Next, let's see it one by one.

For your 'Sample1':
The version is 'InstallShield AFW', which seems to be v6.22 (2000) of InstallShield. As I said in the readme, this program supports from 'DevStudio 9' (2003) to 'InstallShield 2016'.
I thought the old versions should have been supported by the existing tools. And it can be extracted by 7-zip as I [said](https://github.com/Bioruebe/UniExtract2/issues/42#issuecomment-356948614).

For the 'Sample2':
It works. I got the following.
```
C:\Users\...\Desktop\IS_Setup_ICS_011916_1.5.39.173.exe
[0x000C4400]
Dir: "C:\Users\...\Desktop\IS_Setup_ICS_011916_1.5.39.173_u\"
0x00000000 0000803840 "IS_Setup_ICS_011916_1.5.39.173_sfx.exe" ...   Y
0x000C4458 0000010688 "Disk1\0x0404.ini" ...   Y
0x000C6E6C 0000023310 "Disk1\0x0405.ini" ...   Y
0x000CC9CE 0000023896 "Disk1\0x0406.ini" ...   Y
0x000D277A 0000025860 "Disk1\0x0407.ini" ...   Y
0x000D8CD2 0000027384 "Disk1\0x0408.ini" ...   Y
0x000DF81E 0000022492 "Disk1\0x0409.ini" ...   Y
0x000E504E 0000025140 "Disk1\0x040a.ini" ...   Y
0x000EB2D6 0000022724 "Disk1\0x040b.ini" ...   Y
0x000F0BEE 0000026270 "Disk1\0x040c.ini" ...   Y
0x000F72E0 0000025188 "Disk1\0x0410.ini" ...   Y
0x000FD598 0000014884 "Disk1\0x0411.ini" ...   Y
0x00101010 0000014108 "Disk1\0x0412.ini" ...   Y
0x00104780 0000025000 "Disk1\0x0413.ini" ...   Y
0x0010A97C 0000023990 "Disk1\0x0414.ini" ...   Y
0x00110786 0000024330 "Disk1\0x0415.ini" ...   Y
0x001166E4 0000024142 "Disk1\0x0416.ini" ...   Y
0x0011C586 0000023432 "Disk1\0x0419.ini" ...   Y
0x00122162 0000023534 "Disk1\0x041b.ini" ...   Y
0x00127DA4 0000023354 "Disk1\0x041d.ini" ...   Y
0x0012D932 0000023034 "Disk1\0x041f.ini" ...   Y
0x00133380 0000010760 "Disk1\0x0804.ini" ...   Y
0x00135DDC 0000024772 "Disk1\0x0816.ini" ...   Y
0x0013BEF4 0000026308 "Disk1\0x0c0c.ini" ...   Y
0x0014260C 0002797044 "Disk1\data1.cab" ...   Y
0x003ED452 0000148849 "Disk1\data1.hdr" ...   Y
0x00411A19 0038549953 "Disk1\data2.cab" ...   Y
0x028D543A 0000579584 "Disk1\ISSetup.dll" ...   Y
0x02962C8C 0000001238 "Disk1\layout.bin" ...   Y
0x029631BA 0000803840 "Disk1\setup.exe" ...   Y
0x02A27608 0000002760 "Disk1\setup.ini" ...   Y
0x02A28122 0000398486 "Disk1\setup.inx" ...   Y
0x02A8960A 0000360448 "Disk1\setup.isn" ...   Y
extra data:
0x02AE160A 0000006062 "IS_Setup_ICS_011916_1.5.39.173_ext.bin" ...   Y
```

**Comment by mirh** [comment]
:\
Your binary works, but not the one I self-compiled.

**Comment by lifenjoiner** [comment]
It shouldn't be. Maybe there is something wrong with your compilation. I have no idea what's your situation.

**Comment by mirh** [comment]
Ok, I have it. 
VC works. If I use gcc, no can do.

**Comment by mirh** [comment]
Wat? Shouldn't that be a bug or something?

I mean, or at least it was your comments that (among other things) suggested it.

**Comment by lifenjoiner** [comment]
If you always say there is something wrong, but don't show what the problem is, how can anybody help?
I can't reproduce your problem. And my compilations works fine all by tcc/gcc/msvc.

**Comment by mirh** [comment]
Mhh, I see. 
Maybe is because I had 4.9.2 lying around. 
Will see if a newer one can get the job done.
