### ISSUE TITLE
ISx v0.3.7 on Windows XP SP3 x86-32 bit - Decompressing CAB file, fails.

### ISSUE THREAD

**Issue by LordGarfio** [lifenjoiner/ISx#11]
Hello, 
I have unpacked Directory Opus installer (DOpusInstall.exe) from http://gpsoft.com.au/ with success.
However, when I try to unpack the CAB ((data2.cab, data1.cab, data1.hdr)) files, it was not possible.

It is showed the following error about a PE file: "Not-pe-file!".

Additional Info:
1. NOT EXE file
2. CAB v7
3. InstallShield v18 compressed Archive

Thanks in advanced.

**Comment by lifenjoiner** [comment]
CAB files are not supported. There are already other tools for them. Read the `readme.txt`.
