### ISSUE TITLE
The files from _ext.bin are not extracted

### ISSUE THREAD

**Issue by AntonKukoba1** [lifenjoiner/ISx#6]
Well the application kinda works. It produces _sfx.exe and _ext.bin. SFX exe crashes, and it looks like all the files are stored within _ext.bin. Is there any way to extract _ext.bin contents?

**Comment by dubhater** [comment]
Hi!

ISx produced the sfx and ext files. How can I extract them further without running the sfx? 7z doesn't do it.

**Comment by lifenjoiner** [comment]
That is not likely to be an InstallShield installer.

**Comment by dubhater** [comment]
So, the file I'm working with is here: http://en.comfast.com.cn/uploadfile/2022/0610/20220610062026256.zip It contains one file:  ``comfast setup x64.exe``

 I ran ``wine ISx.exe comfast\ setup\ x64.exe``, which printed this:
```
comfast setup x64.exe
[0x0010F400]
Dir: "comfast setup x64_u\"
0x00000000 0001111040 "comfast setup x64_sfx.exe" ...   Y
files total: 6
extracting:
0x0010F45A 0000004607 "???u???O??"
                      can't create file!
extra data:
0x0010F45A 0001016826 "comfast setup x64_ext.bin" ...   Y
```
It produced the two files mentioned.

``strings --encoding=l comfast\ setup\ x64_ext.bin`` shows the following:
```
0x0409.ini
0x0804.ini
1033.mst
2052.mst
COMFAST Wireless Network Adapter.msi
Setup.ini
```
I assume this is where the actual driver files are stored.

``strings --encoding=l comfast\ setup\ x64_sfx.exe`` shows a lot more strings. These are just a few:
```
Preparing Setup>Please wait while the InstallShield Wizard prepares the setup.
```

```
LegalCopyright
Copyright (c) 2020 Flexera. All Rights Reserved.
OriginalFilename
setup.exe
ProductName
COMFAST Wireless Network Adapter
ProductVersion
6.1.13716.6
Internal Build Number
198300
ISInternalVersion
26.0.546
ISInternalDescription
Setup Launcher Unicode
```

I don't even need the driver, I just want to know *what* driver it is.

What do you think? Is there any chance to extract this?

**Comment by lifenjoiner** [comment]
Obviously, @dubhater you used it on a new version installer that was not supported. v0.3.3 has been released.

**Comment by dubhater** [comment]
I see. v0.3.3 extracted the msi. Thank you so much!
