### ISSUE TITLE
program hangs while unpacking

### ISSUE THREAD

**Issue by skochinsky** [lifenjoiner/ISx#7]
Running ISx on [this installer](https://secure-appldnld.apple.com/iPod/ww/win/061-2527.20060629.pidf/iPodSetup.exe) seems to hang on unpacking the "iPod for Windows 2006-06-28.msi" part. Also, some of the unpacked files seem to have wrong content as compared to those dropped by the installer stub  in `%TEMP%`. Is there some kind of additional obfuscation?

**Comment by lifenjoiner** [comment]
Thank you for reporting! Fixed in v0.3.4.

**Comment by skochinsky** [comment]
Awesome, thanks for the quick fix!
