### ISSUE TITLE
_ext.bin file is not extracted completely

### ISSUE THREAD

**Issue by 65wat** [lifenjoiner/ISx#8]
Hi, lifenjoiner,

big fan of your tool. It's the only one that works with current versions of IS.
I recently got my hands on this installer - https://www.swisstransfer.com/d/113e14ac-931b-4c6e-8ea0-0faa553f16da **(3.5 GB, sorry for the huge file but it just comes in one big chunk)** and ISx extracts most of the files in it but stops at an _ext.bin file and doesn't extract it further. It is probably a similar issue as #6 

I understand that this is an edge case and regular installers usually aren't that big, so if you don't wanna download such a huge file, I understand.

**Comment by lifenjoiner** [comment]
Really a big installer!

Fixed in v0.3.6.
