### ISSUE TITLE
Include miniz_tinfl.h and other dependencies in the repo

### ISSUE THREAD

**Issue by voltagex** [lifenjoiner/ISx#9]
Hi,
It's not clear what version of miniz/tinfl is required - miniz_tinfl.h doesn't exist in the original archived miniz 1.14.

**Comment by lifenjoiner** [comment]
I use the full (unmerged) source code rather than the released archive for smaller binaries.

**Comment by voltagex** [comment]
Sure, but which version? That also means you're defining `MINIZ_EXPORT` somewhere

**Comment by lifenjoiner** [comment]
I didn't monitor miniz.
You can create `miniz_export.h` for the latest version with:
https://github.com/richgel999/miniz/blob/293d4db1b7d0ffee9756d035b9ac6f7431ef8492/test.sh#L7-L11
```c
#ifndef MINIZ_EXPORT
#define MINIZ_EXPORT
#endif
```

My previous used version is the master on Dec-25-2017. It doesn't need `miniz_export.h`.
